Update base-de.yaml
tobspr/shapez.io pull request #1183
Opened 2021-06-04 11:21 UTC by HY0077

Habe ein paar Sachen übersetzt.

2021-06-04 11:23 UTC, HY0077 commented
Die überprüfung bleibt immer bei base-pt-BR.yaml hängen.

2021-06-04 11:53 UTC, tobspr requested changes

2021-06-04 11:53 UTC, tobspr commented on translations/base-de.yaml
> +        Hol die den Puzzle DLC auf Steam für noch mehr Spaß!
typo

2021-06-04 12:16 UTC, HY0077 commented
Müsste jetzt passen

2021-06-04 19:54 UTC, DerFeldspatz requested changes
Kleine Änderung, ansonten top 👍

2021-06-04 19:54 UTC, DerFeldspatz commented on translations/base-de.yaml
> +    puzzleMode: Puzzle Modus
Puzzlemodus oder Puzzle-Modus. Alles andere ist Quark.
Ich tendiere für die erste Variante, aber wir sollten eine der beiden konsequent durchsetzen.

2021-06-04 19:54 UTC, DerFeldspatz commented on translations/base-de.yaml
> +    puzzleDlcText: Du hast Spaß daran deine Fabriken zu optimieren und effizienter zu machen?
Du hast Spaß daran, deine

2021-06-05 10:46 UTC, HY0077 commented on translations/base-de.yaml
> +    puzzleMode: Puzzle Modus
Ich finde die erste auch besser

2021-06-05 10:46 UTC, HY0077 commented on translations/base-de.yaml
> +    puzzleDlcText: Du hast Spaß daran deine Fabriken zu optimieren und effizienter zu machen?
Mit Kommas hab ichs nicht so :D

2021-06-05 10:47 UTC, HY0077 commented
So jetzt alles gefixed

2021-06-05 10:58 UTC, DerFeldspatz approved these changes

2021-06-06 06:13 UTC, Aurumaker72 commented on translations/base-de.yaml
> +    puzzleDlcText: Du hast Spaß daran deine Fabriken zu optimieren und effizienter zu machen?
Warum machst du das dann

2021-06-06 10:39 UTC, DerFeldspatz commented on translations/base-de.yaml
> +    puzzleDlcText: Du hast Spaß daran deine Fabriken zu optimieren und effizienter zu machen?
Warum nicht?

2021-06-10 12:04 UTC, HY0077 commented on translations/base-de.yaml
> +    puzzleDlcText: Du hast Spaß daran deine Fabriken zu optimieren und effizienter zu machen?
Man muss ja nicht immer alles perfekt können, so können einem dann ja andere helfen.

2021-06-15 16:35 UTC, HY0077 commented
@tobspr weiß nicht ob du es schon gesehen hast

2021-06-19 11:19 UTC, merged

2021-06-19 11:19 UTC, tobspr commented
Danke!~

2021-06-20 13:55 UTC, HY0077 commented
Kein Problem :)