Update base-de.yaml
tobspr/shapez.io pull request #1190
Opened 2021-06-04 18:11 UTC by Abfqhrt

2021-06-04 19:49 UTC, DerFeldspatz requested changes
Guter Beitrag!
Ein paar kleinere Fehler in der Zeichensetzung und Zusammensetzung eingedeutscher Wörter.
Keine Punkte in Titeln, dafür aber bitte in den Beschreibungen!
Außerdem gibt es ein paar Wörter wie Kurz-Code die schon in der vorhandenen Übersetzung verwendet werden. Aber das du das nicht weißt, ist nicht schlimm.
Wenn du die Änderungen durchführst, bekommst du einen Approve 👍

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        playOffline: Offline Spielen
spielen

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title: Puzzle konnte nicht geladen werden.
Fehler beim Laden des Puzzles

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        descIcon: "Bitte gib einen kurzen Code ein, welcher als Icon für dein Puzzle benutzt wird (Du kannst diese <link>hier</link> erstellen, oder suche dir eines der zufällig generierten Icons aus
Bitte gib hier den Kurz-Code einer Form an. Dieser wird als Icon für das Puzzle verwendet

Punkt in der Klammer muss weg

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        placeholderName: Puzzle Titel
Puzzletitel

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title: Ändern der Größe nicht möglich.
Keine Punkte im Titel

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Du kannst die Zone nicht verkleinern, weil sich dann manche der Gebäude außerhalb der Zone befinden würden
Punkt am Ende

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title: Offline Modus
Offlinemodus

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Wir konnten die Server nicht erreichen, also muss das Spiel im Offline Modus laufen.
Offlinemodus

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Bitte versicher dich, dass du eine aktive Internetverbindung besitzt.
versichere

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title: Download Fehler
Downloadfehler

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: "Downloaden des Puzzles fehlgeschlagen"
Der Download des Puzzles ist fehlgeschlagen.

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: "Konnte dein Puzzle nicht einreichen"
Das Puzzle konnte nicht eingereicht werden.

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title: Offline Modus
Offline-Modus

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Nachdem du offline bist, wird es dir nicht möglich sein dein Puzzle zu speichern oder zu veröffentlichen. Möchtest du trotzdem fortsetzen?
möglich sein, dein Puzzle
trotzdem fortfahren?

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: I empfehle <strong>dringend</strong> das normale Spiel bis Level 12 zu spielen,
Ich empfehle <strong>dringend</strong>, das normale Spiel bis Level 12 zu spielen,

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            bevor du das Puzzle DLC versuchst, sonst wirst du Mechaniken über den Weg laufen welche du noch nicht kennen gelernt hast. Möchtest du trotzdem fortsetzen?
bevor du das Puzzle-DLC versuchst. Du läufst sonst Mechaniken über den Weg, die du noch nicht kennst. Möchtest du trotzdem fortfahren?

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Der Codes des Puzzles (<key>) wrude in deine Zwischenablage kopiert! Er
Der Kurz-Code des Puzzles
wurde in die Zwischenablage

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            kann im Puzzle Menü eingegeben werden um das Puzzle zu erreichen.
Puzzlemenü eingegeben werden, um das

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title: Code eingeben
Kurz-Code

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Gib den Code für das Puzzle ein.
Kurz-Code

2021-06-04 19:49 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            profane: Profan
Ich weiß nicht, ob profan so stark im deutschen Wortschatz der Zielgruppe verankert ist.
Ich würde etwas einfacheres wie `Missbrauch` nehmen

2021-06-05 15:59 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title:
Fehlender Titel

2021-06-09 10:12 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title:
Einfach noch den Titel übersetzen, den hast du bestimmt aus Versehen gelöscht ✌️

2021-06-19 11:23 UTC, tobspr commented
Siehe Anmerkungen von @DerFeldspatz und die Konflikte :)

2021-06-24 17:16 UTC, DerFeldspatz commented
Alle Übersetzungen wurden mitlerweile in #1231 implementiert.

2021-08-04 10:14 UTC, closed without merging