Update base-fr.yaml
tobspr/shapez.io pull request #1207
Opened 2021-06-13 19:12 UTC by DyDyou

i updated all translations of the puzzleMenu (French)  and how could i please if the translations are aprouved.

2021-06-13 22:19 UTC, kionnseur requested changes
first of all, whenever it is written "clé courte" in French, it should be replace by "clé"
(short key to key) since orally it seem disturbing.
I hope others feel same as me.

I have tried here to revise some mistakes, I hope a do a great job ^^

2021-06-13 22:19 UTC, kionnseur commented on translations/base-fr.yaml
> +    short-key-already-taken: Cette touche courte est déjà prise, veuillez en utiliser une autre.
"Cette touche courte" must be replace by "Cette clé" because "touche" refer to a keyboard, not a code that allows access to something

2021-06-14 10:57 UTC, DyDyou commented on translations/base-fr.yaml
> +    profane-title: Le titre de votre puzzle contient des mots profanes.
how I can change the profane word to put forbidden and make changes
please.

2021-06-14 11:01 UTC, DerFeldspatz commented on translations/base-fr.yaml
> +    profane-title: Le titre de votre puzzle contient des mots profanes.
![grafik](https://user-images.githubusercontent.com/57270769/121882132-6b66c480-cd10-11eb-94fc-1f0529911214.png)
You need to go to your repository in the title ( DyDyou:patch-2 ) and push your changes there. It should automatically show the changes here then.

2021-06-19 14:15 UTC, merged

2021-06-19 14:15 UTC, tobspr commented
Cool, thanks!