Updated base-sr.yaml
tobspr/shapez.io pull request #1275
Opened 2021-07-31 23:53 UTC by xTeamStanly

Added all translations for Serbian language. This translation is, to my knowledge, 100% complete.

2021-08-01 07:58 UTC, DerFeldspatz requested changes
Comprehensive changes! They look good to me.
Just check the yaml-lint for trailing whitespace and it seems like you messed up a colon in the syntax.

2021-08-01 12:07 UTC, xTeamStanly commented
Fixed yaml-lint errors. It passes all checks.

2021-08-01 12:20 UTC, DerFeldspatz approved these changes

2021-08-04 10:55 UTC, tobspr commented
Awesome, thank you!

2021-08-04 10:55 UTC, merged