Update base-sv.yaml
tobspr/shapez.io pull request #1314
Opened 2021-11-15 14:11 UTC by Froggi22

Edited and translated to row 412

2021-11-15 15:50 UTC, EmeraldBlock commented on translations/base-sv.yaml
> +    Skaffa pussel-DLCn nu på Steam för ännu mer kul!
seems the indent was lost here?

2021-11-15 15:52 UTC, daanbreur requested changes

2021-11-15 15:52 UTC, daanbreur commented on translations/base-sv.yaml
> +    Skaffa pussel-DLCn nu på Steam för ännu mer kul!
```suggestion
        Skaffa pussel-DLCn nu på Steam för ännu mer kul!
```
He is indeed

2022-02-01 16:27 UTC, merged

2022-02-01 16:27 UTC, tobspr commented
Thanks!