Allow external URL to load more than one mod
tobspr/shapez.io pull request #1337
Opened 2022-01-18 16:13 UTC by Bagel03

Instead of loading the text returned from the remote server, load a JSON object with a `mods` field, containing strings of all the mods. This lets us work on more than one mod at a time or without separate repos. This will break tooling such as `create-shapezio-mod` though.

2022-01-18 16:15 UTC, DJ1TJOO commented
I do not think this is necessary. Most users will only be developing one mod at a time.

2022-01-18 16:16 UTC, Bagel03 commented
Maybe not developing but it would help to have 1 repo `<name> shapez mods` rather than a bunch of smaller ones and multiple copies of the game

2022-01-18 16:17 UTC, DJ1TJOO commented
You could also use git branches

2022-01-18 16:17 UTC, EmeraldBlock commented
would agree that loading multiple mods could be useful (maybe they're related, or you want to test how they interact, or something), but I think JSON's a bit hacky for that

2022-01-18 16:19 UTC, Bagel03 commented
Yea Emerald, I agree, but I could not think of another way that would be less hacky and I could write in the span of my English class 😄

2022-01-18 16:20 UTC, EmeraldBlock commented
so that's why it's a verified commit 🤔

2022-01-18 17:38 UTC, tobspr commented
I'd prefer if the externalModUrl could be either string or string[]

2022-01-18 17:56 UTC, Bagel03 commented
Good idea, I have math next so I'll try to do it then

2022-01-18 21:38 UTC, Bagel03 commented
Math was a little busy, this should work 👍

2022-01-20 16:54 UTC, tobspr requested changes

2022-01-20 16:54 UTC, tobspr commented on src/js/mods/modloader.js
> +            for(let i = 0; i < modURLs.length; i++) {
can you fix the spacing

2022-01-20 16:54 UTC, merged