Performance settings section translation
tobspr/shapez.io pull request #622
Opened 2020-08-31 20:44 UTC by Withers001-1

Added the translation for the new settings performance-related in the Alpha, and made part of the file look cleaner.

2020-08-31 22:48 UTC, DerFeldspatz requested changes

2020-08-31 22:48 UTC, DerFeldspatz commented on translations/base-fr.yaml
> +
You need to remove all the spaces in a free line. This also applies to lines 732, 749, 754, 763, 769, 775, 780, 785 and 790. You can look this up from the error messages in the CI check

2020-08-31 22:48 UTC, DerFeldspatz commented on translations/base-fr.yaml
> +       compactBuildingInfo:
There is one space missing here in front (for a total of 8).

2020-09-12 12:24 UTC, LeopoldTal commented on translations/base-fr.yaml
> +                Simplifie le rendu des ressources sur la carte lorsqu'elle est zoomée opur améliorer les performances.
typo: `opur` -> `pour`

2020-09-12 12:24 UTC, LeopoldTal commented on translations/base-fr.yaml
> +                Activé par défaut, efface le curseur lorsque vous faites un clic droit en ayant un bâtiment selectioné pour la constructio. Si desactivé, vous pouvez detruire les bâtiments en faisant
typo: `constructio` -> `construction`

2020-09-12 12:25 UTC, LeopoldTal commented on translations/base-fr.yaml
> +            title: Monter les bordures de chunks
Inconsistent choice of vocabulary here

2020-09-12 12:25 UTC, LeopoldTal commented on translations/base-fr.yaml
> +            title: Desactiver la grille de placement
Typo: `Desactiver` -> `Désactiver` (throughout)

2020-09-12 12:26 UTC, LeopoldTal commented on translations/base-fr.yaml
> +                Desactiver la grille de placement peut aider les performances. Ça rend aussi le jeu encore plus uni!
Kinda unclear

2020-09-13 07:13 UTC, tobspr commented
I'll merge it for now, feel free to fix it with another pr @LeopoldTal ! :)

2020-09-13 07:14 UTC, merged