Update base-de.yaml
tobspr/shapez.io pull request #624
Opened 2020-09-01 07:53 UTC by LordJakson

Unklare Tastenbelegungen besser beschrieben

2020-09-01 08:08 UTC, DerFeldspatz requested changes

2020-09-01 08:08 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        cycleBuildingVariants: nächste Variante auswählen
`Nächste` großschreiben

2020-09-01 08:08 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        cycleBuildings: nächstes Gebäude auswählen
s.o.

2020-09-01 08:58 UTC, DerFeldspatz approved these changes
Gut aufgepasst! :)

2020-09-13 07:15 UTC, tobspr commented
Danke!

2020-09-13 07:15 UTC, merged