Update base-nl.yaml
tobspr/shapez.io pull request #722
Opened 2020-09-30 15:03 UTC by Underlyingglitch

Full translation to dutch.

2020-09-30 17:11 UTC, daanbreur requested changes

2020-09-30 17:11 UTC, daanbreur commented on translations/base-nl.yaml
> +    title_advantages: Losstaande Voordelen
leave this `Standalone`

2020-09-30 17:11 UTC, daanbreur commented on translations/base-nl.yaml
> +        - Puzzle Modus
`puzzle` is english
`puzzel` is dutch

2020-09-30 17:11 UTC, daanbreur commented on translations/base-nl.yaml
> +        discord: Officiele Discord
You write it with the 2 dots. So don't Remove them

2020-09-30 17:11 UTC, daanbreur commented on translations/base-nl.yaml
> +        limited_items: Limiet ingesteld op: <max_throughput>
This must be `Gelimiteerd op`

2020-09-30 20:15 UTC, RemcoStamHub commented
Can confirm all comments of daanbreur are correct.

2020-09-30 21:03 UTC, Underlyingglitch commented
@daanbreur You made some very good comments. Indeed thy are correct. Sorry I missed those. Now, I’m new to github pull requests: do I have to change this? If so please let me know,I would be happy to do so!

2020-10-01 06:01 UTC, daanbreur commented
Go to your local fork. github.com/<username>/shapez.io

Then change the branch from `master` to `patch-1`. ( there is a little selector at the top of the page) 

Then just navigate to the Dutch translation file. And make the edits. All commits on that branch (patch-1) will be added to this PR.

2020-10-01 06:02 UTC, daanbreur commented on translations/base-nl.yaml
> +        limited_items: Limiet ingesteld op: <max_throughput>
Or `Gelimiteerd tot`

2020-10-01 06:18 UTC, tobspr commented
I'll make the adjustments - thanks a lot to all of you!

2020-10-01 06:18 UTC, merged

2020-10-01 06:52 UTC, daanbreur commented
Thanks...