Dockerfile use for Node12
tobspr/shapez.io pull request #727
Opened 2020-09-30 18:10 UTC by endofzero

I've been using this dockerfile successfully to build and run Shapez.io without needing to install and maintain node.

Building is straight forward: "docker build -t shapezio ."

After building you and start and stop the image whenever you need to.

Running is just as straight forward: "docker run --name="shapezio" --rm -p 3005:3005 shapezio"

To stop the instance: "docker stop shapezio"

Due to --rm the instance should be deleted once stopped.

If you want to stop the messages about not being able to open the browser, you can edit line 155 of gulp/gulpfile.js, and add
"open: false," 
It shouldn't affect anything having it still there, but altering it may mess up future pull requests so I would suggest leaving it as is and just ignore the warning.

function serve({ standalone }) {
    browserSync.init({
        server: buildFolder,
        port: 3005,
        ghostMode: {
            clicks: false,
            scroll: false,
            location: false,
            forms: false,
        },
        logLevel: "info",
        logPrefix: "BS",
        online: false,
        **open: false,**
        xip: false,
        notify: false,
        reloadDebounce: 100,
        reloadOnRestart: true,
        watchEvents: ["add", "change"],
    });

2020-10-01 06:24 UTC, tobspr requested changes

2020-10-01 06:24 UTC, tobspr commented on Dockerfile
> +RUN git-lfs pull
I just recently got rid of git-lfs, so I think you can remove that :)

2020-10-01 06:24 UTC, tobspr commented
Looks good except for a minor change! :)

2020-10-02 02:16 UTC, endofzero commented on Dockerfile
> +    && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
```suggestion
    && rm -rf /var/lib/apt/lists/* 
```

2020-10-02 09:13 UTC, tobspr commented
There's still a git-lfs pull command inside :)

2020-10-04 08:25 UTC, tobspr commented
Nice, thank you!

2020-10-04 08:25 UTC, merged