Update base-de.yaml
tobspr/shapez.io pull request #760
Opened 2020-10-04 12:53 UTC by everthingArduino

Translated the rest for the new update

2020-10-04 13:44 UTC, DerFeldspatz requested changes

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        Performance!
Es geht nicht nur um Performance, sondern auch um Features -> Erfahrung

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Du löscht viele Gebäude! (<count> um genau zu sein) Bist du dir
Satzzeichen kommen immer nach den Klammern

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Du schneidest viele Gebäude aus! (<count> um genau zu sein) Bist du
^

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Blaupausen werden erst nach Level 12 freigeschaltet!
Wenn dann `mit`. `in` macht hier schon Sinn

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            seperate Ebene über der regulären Ebene und kommt mit vielen neuen Mechaniken!
mit `on top` ist hier nicht `über` gemeint, sonden `neben` oder `zusätzlich zur`. Die Kabelebene befindet sich unter den Gebäuden

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            <br><br> Für den Anfang habe ich dir den <strong>Quad Färber</strong>
`vierfachen Färber` oder `Vierfach-Färber`. Bindestrich ist hier ein Muss.

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            freigeschaltet - Verbinde die Slots mit denen du malen willst mit der Kabelebene!<br><br>
`die Slots, mit denen du malen willst, mit` Interpunktion. `möchtest` klingt freundlicher

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            freigeschaltet - Verbinde die Slots mit denen du malen willst mit der Kabelebene!<br><br>
Ich habe in der Übersetzung fast alle Bindestriche durch Satzzeichen ersetzt, also auch hier bitte durch ein Ausrufezeichen ersetzen und den folgenden Satz mit einem Punkt beenden

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
>          title: Item Filter
Bindestrich ist Pflicht

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
>          title: Item Filter
Oder viel besser: Du schreibst es zusammen

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Du hast den <strong>Item Filter</strong> freigeschaltet! Die Items werden
^

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            einem Boolean-Signal(1 / 0) aktivieren oder komplett ausschalten.
`Boolschen Signal`, wenn du es übersetzen willst

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            einem Boolean-Signal(1 / 0) aktivieren oder komplett ausschalten.
In Klammern bitte durch `(1 oder 0)` ersetzten (Konsistenz).

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            einem Boolean-Signal(1 / 0) aktivieren oder komplett ausschalten.
`komplett` muss hier nicht stehen (an/aus ist schon absolut)

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
>          title: Display
Anzeige

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: "Du hast das <strong>Display</strong> freigeschaltet - Verbinde es
^

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: "Du hast das <strong>Display</strong> freigeschaltet - Verbinde es
Interpunktion, s.o.

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            mit einem Signal auf der Kabelebene um es anzuzeigen!<br><br> PS:
`Kabelebene, um` Interpunktion

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            gelesene Item ausgeben? Versuche es an einem Display anzuzeigen!"
Anzeige

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            gelesene Item ausgeben? Versuche es an einem Display anzuzeigen!"
dann kannst du `anzeigen` durch `darstellen` oder `ausgeben` ersetzen

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title: Konstantes Signal
Signalgeber

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Du hast das <strong>Konstantes Signal</strong> Gebäude auf der
^

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Kabelebene freigeschaltet! Du kannst es mit Item Filtern verbinden z.B.<br><br>
`Du kannst es zum Beispiel mit` oder du kürzt mit z.B. ab. Aber am Ende des Satzes passt das nicht

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Kabelebene freigeschaltet! Du kannst es mit Item Filtern verbinden z.B.<br><br>
`Item-Filtern`

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        title: Logikschaltungen
Logikgatter

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +        desc: Du hast <strong>Logikschaltungen</strong> freigeschaltet! Du musst
^

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Mit diesen Schaltungen kannst du jetzt AND, NOT, OR und XOR Operationen berechnen.
`Operationen durchführen` ?

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            <br><br> Und als extra Bonus oben drauf habe ich dir noch einen <strong>Transistor</strong> gegeben!
`extra Bonus` doppelt sich. Außerdem würde ich das `oben drauf` würde ich vor gegeben packen

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Damit hast du nun 3 Optionen wie du weiter spielen kannst:<br><br> -
`Optionen, wie` Interpunktion

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Baue eine <strong>Vollautomatische Maschine</strong> um alle von der HUB angefragten
`vollautomatisch` Großschreibung

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Baue eine <strong>Vollautomatische Maschine</strong> um alle von der HUB angefragten
`Hub` ist eingedeutscht und wird auch in der ganzen Übersetzung verwendet

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Baue eine <strong>Vollautomatische Maschine</strong> um alle von der HUB angefragten
`, um` Interpunktion

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Formen zu kreieren (Ich empfehle dir, es mal auszuprobieren!).<br><br> -Baue irgendwas,
`(Probiere es am besten aus)` ?

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Formen zu kreieren (Ich empfehle dir, es mal auszuprobieren!).<br><br> -Baue irgendwas,
Leerzeichen nach dem Bindestrich

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            Formen zu kreieren (Ich empfehle dir, es mal auszuprobieren!).<br><br> -Baue irgendwas,
`irgendwas richtig` Interpunktion

2020-10-04 13:44 UTC, DerFeldspatz commented on translations/base-de.yaml
> +            was du auswählst, vergiss nicht dabei Spaß zu haben!
`vergiss dabei den Spaß nicht!` ?

2020-10-04 22:58 UTC, KaiSforza commented on translations/base-de.yaml
> +        desc: Ich habe einen ganzen Haufen an neuen Gebäuden hinzugefügt, mit denen du die
Trailing spaces here

2020-10-04 22:58 UTC, KaiSforza commented on translations/base-de.yaml
> +            Das Konstante Signal kann eine <strong>Form</strong>, <strong>Farbe</strong>
Trailing spaces here

2020-10-04 22:59 UTC, KaiSforza commented on translations/base-de.yaml
> +            Formen zu kreieren (Ich empfehle dir, es mal auszuprobieren!).<br><br> -Baue irgendwas,
Trailing spaces here, too.

2020-10-04 22:59 UTC, KaiSforza commented on translations/base-de.yaml
> +            richtig Cooles mit Kabeln.<br><br> - Einfach wie davor weiter spielen.<br><br> Egal
trailing spaces on these two lines.

2020-10-06 12:44 UTC, tobspr commented
Hey, bitte schau nochmal drüber, die Übersetzung scheint noch nicht wirklich zu passen. Schließe mich @DerFeldspatz an. Vielleicht kommuniziert ihr erstmal, da er der Haupt-Übersetzer ist! :)

2020-10-06 12:44 UTC, closed without merging