Hello! I'd like to help localizing / Japanese text
tobspr/shapez.io pull request #919
Opened 2020-10-21 14:57 UTC by floatingfragmentz

Hello sir,

I'd prepared updated text which is in Japanese. and like appreciate if you considered check this.

# note
In Japanese text, some sentence was not translated yet. 
(Maybe, it's remained due to upgrading versions)

Thanks,
RANDO:

2020-10-21 17:30 UTC, LeopoldTal requested changes

2020-10-21 17:30 UTC, LeopoldTal commented on translations/base-ja.yaml
> +            1_2_conveyor: 抽出機を <strong>コンベアベルト</strong> でHUBまで繋げましょう！<br><br> Tip:
This is a syntax error. Put the quotes back in.

2020-10-21 17:30 UTC, LeopoldTal commented on translations/base-ja.yaml
> +            <strong>E</strong>キーを押してください。 <br><br>
Trailing spaces here and next line

2020-10-21 17:30 UTC, LeopoldTal commented on translations/base-ja.yaml
> +            出力していることをお気づきでしたか?
Trailing space

2020-10-22 11:32 UTC, floatingfragmentz commented
Thank you very much for suggesting!!

2020-10-22 12:26 UTC, floatingfragmentz commented
An issue of Japanese lang file has solve, but other lang has issue. so please let me know if I have to do. 
Thanks

2020-10-23 06:57 UTC, Nucleareal commented
There is two translation PR (#876, #919) based on tobspr's master
And what should I do?

2020-10-31 11:25 UTC, tobspr commented
Seems there are conflicts now, can you have a look?

2020-11-01 17:14 UTC, Nucleareal commented
This is conficted but many good translations are there, 
and if any reactions are nothing until 11/05/20, I make new PR that contains these (these good translation) based on now master.

2020-12-07 17:30 UTC, tobspr commented
Okay closing this now

2020-12-07 17:30 UTC, closed without merging